### ISSUE TITLE
[BE] 리뷰 작성 페이지에서 리뷰 그룹에 대한 잘못된 정보가 나오는 버그

### ISSUE THREAD

**Issue by nayonsoso** [woowacourse-teams/2024-review-me#1002]
### 🔍 설명이자 시말서
일단 아래 방법으로 정상화했습니다.

1. develop 브랜치에서 버그를 해결해서 hotfix/cache-key로 푸쉬 
2. dev CD 를 hotfix/cache-key 위에서 돌림
3. dev 서버에서 정상 작동 확인
4. prod cd 에서는 runner가 제대로 설정되지 않았었기에, release-hotfix/change-runner 브랜치에서 이를 수정 https://github.com/woowacourse-teams/2024-review-me/commit/cda7037c5b28e141761a92c5f7641ba2c7631178
5.  prod CD 를 release-hotfix/change-runner 브랜치 위에서돌림
6. prod 서버 정상 작동 확인

((다시 돌아보니 사실 1~3번 과정은 필요 없었던 것 같습니다))

### 문제 원인과 해결
1. **cache key가 잘못 설정되어있었습니다.**
➡️ cache key 수정 PR 올렸습니다. https://github.com/woowacourse-teams/2024-review-me/pull/1003

2. **prod 서버가 dev 브랜치의 코드로 배포되어 있었습니다 😱**
release 브랜치에서는 스프링 캐시 관련된 코드가 한줄 없는 상태입니다. 
따라서 1번 문제가 애초에 생기면 안되는 것이었습니다.
하지만 저와 커비가 무중단 배포를 실험하면서 develop 브랜치 위에서 release cd 를 돌렸습니다.
이 때문에 prod 서버에서 완전하지 않은 상태의 dev 코드 돌았고, 1번 문제가 발생했습니다.
➡️ release cd 브랜치를 제한하는 PR 올렸습니다. https://github.com/woowacourse-teams/2024-review-me/pull/1004

3. **prod cd 의 runner를 develop 브랜치에서는 바꿨는데, 이를 release에 머지하지 않았습니다.** 35d7530cf473f7f6e48b555ca119c02beda6ba1f
➡️ 1번 머지되고, QA를 거친 다음, release <- develop 머지하면 해결됩니다.

4. **oracle-prod-runner 가 제대로 작동되지 않았습니다.**
 release 브랜치 위에 cd를 돌려도 job을 잡아가지 못했습니다.
https://github.com/woowacourse-teams/2024-review-me/actions/runs/12321141214
![image](https://github.com/user-attachments/assets/50e9a243-3b92-4866-b3a1-f76ef112172b)
➡️ 지우고 다시 깔아서 해결했습니다.

### 🔥 할 일
- PR 리뷰 부탁드려요!

### ⏰ 예상 시간
- 대부분 이미 완료

### 🐴 할 말
- 인프라 마이그레이션이 제대로 마무리되지 않았어서 문제가 여러군데에서 발생했네요 죄송합니다...😔

**Comment by donghoony** [comment]
- #1008 에서 해결되었습니다~
