### ISSUE TITLE
[BE] 연관관계 기준에 따라 리팩터링한다.

### ISSUE THREAD

**Issue by hyeonji1220** [woowacourse-teams/2024-review-me#12]
### 🔍 설명
- 현재 엔티티에 적용되어있는 연관관계를 끊는 것이 나을지 고민한다.
- 엔티티가 객체지향적 관점에서 괜찮은지 고민한다.

### 🔥 할 일
- 백엔드끼리 모였을 때 논의 후 결과 코드에 적용하기

### ⏰ 예상 시간
- 30분

**Comment by donghoony** [comment]
#83
