### ISSUE TITLE
[BE] Dto 위치 논의

### ISSUE THREAD

**Issue by nayonsoso** [woowacourse-teams/2024-review-me#160]
### 🔍 설명
- 글로벌 패키지에 Dto가 있으면 안 될 것 같습니당... 사용하는 곳에 존재해야 한다고 생각해용용
- Dto 패키지가 서비스에 있는 게 맞을까요, 컨트롤러 패키지에 있는 게 맞을까요? 저는 컨트롤러는 아닌 것 같아요 (산초)
- 저는 서비스에 있어야 할 것 같아요(아루)
- 컨트롤러에 존재하면 의존성의 방향이 옳지 않다고 생각했습니다 (서비스에서 컨트롤러의 dto를 사용함, 패키지 양방향 참조) 
 
### 🔥 할 일
- 논의하기

### ⏰ 예상 시간
- 30초

### 🐴 할 말
- 히히힝

**Comment by donghoony** [comment]
서비스에 있으면 좋겠다- 로 모아졌으나, Swagger API 어노테이션이 붙는 게 참 별로네요.. 😢

**Comment by nayonsoso** [comment]
이것도 나중에 논의하기로 미뤄짐!!
