### ISSUE TITLE
[BE] 제약사항 및 정책을 도메인 객체 또는 서비스에 위임한다.

### ISSUE THREAD

**Issue by donghoony** [woowacourse-teams/2024-review-me#21]
### 🔍 설명
- 현재 다양한 정책이 반영되어있지 않아 테스트에 어려움을 겪고 있습니다 (무엇을 테스트해야할지에 대한 고민)
- 다음과 같은 요구사항을 추가하고자 합니다.

### 🔥 할 일
회원은 리뷰어 그룹을 만들 수 있다.
- [x] #61
- [x] 리뷰어 그룹에 리뷰이는 포함될 수 없다.
- [x] 리뷰어는 깃허브에 존재한다면, 서비스에 가입하지 않아도 추가할 수 있다.
- [ ] 리뷰어 그룹에는 깃허브 레포지토리를 연동한다. 그룹 이름은 레포지토리 이름이다.
- [x] 리뷰어 그룹 설명을 작성할 수 있다.
- [x] 리뷰어 그룹은 리뷰 작성 마감기한이 존재한다.

리뷰어 그룹에 속한 회원은 리뷰를 작성할 수 있다.
- [x] 리뷰어 한 명당 하나의 리뷰만 작성할 수 있다. (중복 작성 불가)
- [x] 그룹 리뷰 작성 마감기한이 지나면 리뷰를 작성할 수 없다. (POST 시각 검증, 추가 url 없앰)
- [x] 리뷰어는 리뷰를 작성한 뒤, 주어진 키워드 중 리뷰이에게 어울리는 키워드를 최대 3개 고를 수 있다.
- [x] 그룹에 속하지 않은 회원은 리뷰를 작성할 수 없다 (권한)

리뷰는 여러 질문과 그에 대한 답변으로 이루어져 있다.
- [x] 답변은 공백이어서는 안 된다.
- [x] (미확정) 질문은 제공되는 것을 활용하거나, 리뷰이가 추가할 수 있다.

리뷰이는 리뷰어가 작성한 리뷰를 확인할 수 있다.
- [x] 기본적으로 익명이다.
- [x] 리뷰 상세를 확인할 때, 질문에 대한 답변과 리뷰어가 남긴 키워드가 표시된다.

### ⏰ 예상 시간
- 2시간?

**Comment by nayonsoso** [comment]
### 리뷰어 그룹

- 회원은 리뷰어 그룹을 만들 수 있다.
- 리뷰어 그룹은 최소 1명 이상의 리뷰어로 구성되어 있다. 
  - 이 검증을 어디에서 할 것인지? 도메인을 생성할 때?
- 리뷰어는 서비스에 가입하지 않아도 추가할 수 있다 (깃허브에 존재해야 한다) 
  - 리뷰어 그룹을 만들 때 리뷰 매핑이 생성되는데, 그때 깃허브 아이디가 추가되어야 한다.
- 리뷰어 그룹에는 깃허브 레포지토리를 연동한다. 
  - url 컬럼 추가해야 한다.
- 리뷰어 그룹 이름은 레포지토리 이름이다. 
- 리뷰어 그룹 설명을 작성할 수 있다.
  - 최소, 최대 글자 정해야 한다.
- 리뷰어 그룹은 리뷰 작성 마감기한이 존재한다. 
  - 마감 기한은 그룹 생성으로부터 7일로 정하기로 했었다!
- 리뷰어 그룹에 속한 회원은 리뷰를 작성할 수 있다. 
  - 작성을 할 때 검증을 해야 한다.
- 그룹 리뷰 작성 마감기한이 지나면 리뷰를 작성할 수 없다.
   - 리뷰를 쓸 때 검증 로직 추가해야 한다.
- 리뷰어 그룹에 리뷰이는 포함될 수 없다.
  - 리뷰를 쓸 때 검증 로직 추가해야 한다.
- 그룹에 속하지 않은 회원은 리뷰를 작성할 수 없다 (권한)
  - 리뷰를 쓸 때 검증 로직 추가해야 한다.

### 리뷰 작성
- 리뷰어 한 명당 하나의 리뷰만 작성할 수 있다.
  - 리뷰를 쓸 때 검증 로직 추가해야 한다.
- 리뷰어는 리뷰를 작성한 뒤, 주어진 키워드 중 리뷰이에게 어울리는 키워드를 최대 3개 고를 수 있다.
  - 최대를 5개로 정하긴 했었다!
- 리뷰는 여러 질문과 그에 대한 답변으로 이루어져 있다.
- 답변은 공백이어서는 안 된다.
  - 리뷰를 쓸 때 검증 로직 추가해야 한다.

### 리뷰 확인
- 리뷰이는 리뷰어가 작성한 리뷰를 확인할 수 있다.
- 기본적으로 익명이다.
- 리뷰 상세를 확인할 때, 질문에 대한 답변과 리뷰어가 남긴 키워드가 표시된다.

**Comment by donghoony** [comment]
Github username, Repository URL은 변동 가능성이 존재하므로, Github에서 고유한 식별자를 사용해야 합니다.
- Github user ID: https://api.github.com/users/donghoony 의 `id` 
<img width="341" alt="image" src="https://github.com/user-attachments/assets/452c2b5e-9e9b-41a2-9005-d2d2083455c9">

- Repository ID: https://api.github.com/repos/donghoony/milky-way 의 `id`
<img width="393" alt="image" src="https://github.com/user-attachments/assets/8ef98411-69ae-4076-88a6-56b0b34690d1">

User ID로 Github user 찾기: https://api.github.com/user/31026350
Repo ID로 Repository 찾기: https://api.github.com/repositories/819051346

**Comment by nayonsoso** [comment]
### 도메인
- [ ] 답변은 공백이어서는 안 된다.

### 서비스
- [x] 리뷰어 그룹에 속한 회원은 리뷰를 작성할 수 있다.
- [x] 리뷰어 한 명당 하나의 리뷰만 작성할 수 있다. (중복 작성 불가)
- [ ] 그룹 리뷰 작성 마감기한이 지나면 리뷰를 작성할 수 없다. (POST 시각 검증, 추가 url 없앰)
- [x] 그룹에 속하지 않은 회원은 리뷰를 작성할 수 없다 (권한)
- [ ] 기본적으로 익명이다.

### 양방향 (or 서비스)
- [ ] 리뷰어 그룹에 리뷰이는 포함될 수 없다.
- [ ] 리뷰어 그룹은 최소 1명 이상의 리뷰어로 구성되어 있다.

### 키워드 양방향?? 리스트?? 리뷰에서 키워드가 필요하다??
- [ ] 리뷰어는 리뷰를 작성한 뒤, 주어진 키워드 중 리뷰이에게 어울리는 키워드를 최대 3개 고를 수 있다.

### 아직 안해도 되는 것
- [ ] 리뷰어는 깃허브에 존재한다면, 서비스에 가입하지 않아도 추가할 수 있다.
- [ ] 리뷰어 그룹에는 깃허브 레포지토리를 연동한다. 그룹 이름은 레포지토리 이름이다.
- [ ] (미확정) 질문은 제공되는 것을 활용하거나, 리뷰이가 추가할 수 있다.

### 이미 한 것
- [x] 리뷰어 그룹 설명을 작성할 수 있다.
- [x] 리뷰어 그룹은 리뷰 작성 마감기한이 존재한다.

**Comment by donghoony** [comment]
#62 #63 #64 으로 구체화합니다.
