### ISSUE TITLE
[BE] 로그를 위한 Loki를 적용한다. 

### ISSUE THREAD

**Issue by hyeonji1220** [woowacourse-teams/2024-review-me#227]
### 🔍 설명
- 

### 🔥 할 일
- 

### ⏰ 예상 시간
- 

### 🐴 할 말
- 정리 자료 https://longing-mastodon-de7.notion.site/Loki-0b4ac99abdc74950aceb903f49d38e22?pvs=4

**Comment by donghoony** [comment]
적용 완료!
