### ISSUE TITLE
[FE] 리뷰 작성 페이지 카드, 질문 공통 컴포넌트를 만들고, 슬라이더 방식의 카드 전환 기능을 추가한다.

### ISSUE THREAD

**Issue by soosoo22** [woowacourse-teams/2024-review-me#232]
### 🔍 설명
- 리뷰 작성 페이지 공통 컴포넌트를 만들고, 슬라이더 방식의 카드 전환 기능을 추가한다.

### 🔥 할 일
* [ ] 카드 컴포넌트
* [ ] 질문 컴포넌트
* [ ] 슬라이더 기능

### ⏰ 예상 시간
- 1시간

### 🐴 할 말
- 공통 컴포넌트? 금방 끝내줄게^^

**Comment by donghoony** [comment]
#247
