### ISSUE TITLE
[BE] 초기 데이터 설정시 중복 삽입 방지, 선택지 최대 갯수 적용

### ISSUE THREAD

**Issue by hyeonji1220** [woowacourse-teams/2024-review-me#314]
### 🔍 설명
- 초기 데이터 설정시 중복 삽입 방지, 선택지 최대 갯수 적용

### 🔥 할 일
- 초기 데이터 설정시 서버가 켜질 때마다 초기 데이터가 삽입됩니다. 기존 데이터가 있으면 삽입하지 않는 로직을 추가해야합니다.
- 꼬리질문 객관식 최대 선택 갯수를 3개로 수정합니다.
- 꼬리질문 서술형 질문 내용을 수정합니다. : `위에서 선택한 사항과 관련된 경험을 구체적으로 적어 주세요.`

### ⏰ 예상 시간
- 1시간?

### 🐴 할 말
-

**Comment by donghoony** [comment]
현재 상황: MySQL 직접 들어가서 업데이트 날리는 중. 존재하지 않으면 한 번만 추가하는 기능이 필요할 듯.

**Comment by donghoony** [comment]
`위에서 선택한 사항과 관련된 경험을 구체적으로 적어 주세요.`

**Comment by donghoony** [comment]
최대 3개 고정

**Comment by hyeonji1220** [comment]
1. prod
 현재는 임시방편이므로 추후 
- sql root에서 데이터 추가하거나(다른 user의 수정 권한 없애기) 
- admin 페이지를 만들어서 추가하게 하거나(u,d api 필요) 
2. dev:  이미 템플릿이 있으면 추가하지 않는 로직을 DataInitializer에 추가
```java
// 템플릿이 이미 존재하면 종료
if (templateRepository.existsById(1L)) {
    return;
}
```
