### ISSUE TITLE
[BE] entity의 필드 null 검증을 어떻게 할 것인지 논의한다.

### ISSUE THREAD

**Issue by nayonsoso** [woowacourse-teams/2024-review-me#33]
### 🔍 설명
@nayonsoso 와 @donghoony 와 도메인의 생성자에 넣을 검증 로직을 작성하는 중, 논의의 필요성을 느꼈습니다.

문자열 타입의 컬럼에 NULL 이 들어오는 것을 막기 위해서 어떤 방법을 사용해야 할까요?
1. ddl 의 nullable = false 로도 충분하다.
2. 데이터베이스에 들어가려 하기 전에, 어플리케이션에서 잡는게 좋다. 자바 빈 validation인`@NotNull` 을 걸어주자. [밸덩](https://www.baeldung.com/java-validation)
3. 2번의 방법은 의존성이 필요하고, 순수하게 자바로 동작하는 것이 아니기 때문에 private 함수로 검증해야 한다.

### 🔥 할 일
- null이 올 때 '예외를 던지는 곳은 어디가 되어야 할지' 이야기해봐야 합니다.
- null이 올 때 '어떤 방법으로 예외를 던질지' 이야기해봐야 합니다.

### ⏰ 예상 시간
- 희망편 : 논의 20분, 리팩터링 20분
- 절망편 : 논의 30분, 리팩터링 30분

### 🐴 할 말
- 히히힝~~ 이거슨 모든 구성원들이 Jakarta bean validation과 spring validation 에 대해 학습하고 진행해야 할 것 같습니다~ [참고](https://velog.io/@happyjamy/Spring-%EC%9D%B4-Bean-validation-%EC%9D%84-%EC%88%98%ED%96%89%ED%95%98%EB%8A%94-%EB%B2%95-Hibernate-Validator-%EC%99%80-Spring-Validator-%EC%B0%A8%EC%9D%B4)

**Comment by nayonsoso** [comment]
### 🧑🏻‍⚖️ 7월 18일 목요일 오전에 논의가 종결되었습니다!!!

- 논의 내용 : Null 이나 Size 검증을 어떻게 할 것인가? 어디서 할 것인가?

- 결론 : Dto 와 DDL 에서만 하자
  - Request Dto 에 jakarta.validation 어노테이션을 달고, 
  - Controller 에 org.springframework.validation의 @Valid 와 BindingResult 를 붙이고
  - ControllerAdvice 에서 ConstraintViolationException 를 핸들링 하자.


### 🙋🏻‍♀️ 나왔던 의견 : jakarta.validation 어노테이션를 엔티티의 필드에 달아 insert 문이 나가기 전에 예외를 던지자.
- query 문 하나 더 나가는 것을 막기 위해 어노테이션을 여러곳에 다는게 더 이상한 것 같다. 라는 반대 의견이 있었다.
- 그리고 일단은 기능 구현에 속도를 올리기 위해서라도, DTO 에만 어노테이션을 달자고 의견이 좁혀졌다.

**Comment by donghoony** [comment]
조금 더 논의:

- `null, empty`와 같은 입력 형식만 검증한다.
- 글자 수와 같은 정책적인 사항은 도메인에서 검증한다.
