### ISSUE TITLE
[BE] Fixture 를 만들어서 테스트 작성을 수월하게 한다.

### ISSUE THREAD

**Issue by nayonsoso** [woowacourse-teams/2024-review-me#377]
### 🔍 설명
- 여러가지 경우에 대해 테스트하기 수월하게 하기 위해 테스트 Fixture 를 만들 필요가 있습니다.

### 🔥 할 일
- Fixture 만들기!
- Fixture 적용해서 기존 테스트 코드 리팩터링 하기

### ⏰ 예상 시간
- 2시

### 🐴 할 말
-

**Comment by donghoony** [comment]
#524 👍🏻
