### ISSUE TITLE
[BE] ERROR 로그가 특정 개수 이상 쌓인다면 & CPU 사용량이 기준을 초과하면 60% 초과하면 & 메모리도 (산초가 정해서)알림을 보낸다.

### ISSUE THREAD

**Issue by nayonsoso** [woowacourse-teams/2024-review-me#393]
### 🔍 설명
- ERROR 로그의 갯수에 따라서 알림을 주는 기능을 구현합니다.
- 실 사용자들이 생기기 전까지만 구현을 하면 될 것 같습니다.

### 🔥 할 일
- 그라파나에서 디스코드로 알림을 주는 방법이 있는지 찾아봅니다.

### ⏰ 예상 시간
- 3시간

### 🐴 할 말
- 그라파나의 알림 기능을 적극 활용해봅시다!!

**Comment by nayonsoso** [comment]
프로메테우스 allert 사용해보기

**Comment by Kimprodp** [comment]
Prometheus의 Alerting 시스템 참고하면 좋을 듯 합니다! (Loki는 어쩌지?)

**Comment by donghoony** [comment]
고생했어요 산초~
