### ISSUE TITLE
[FE] 점을 뺀다.

### ISSUE THREAD

**Issue by chysis** [woowacourse-teams/2024-review-me#438]
### 🔍 설명
- 에러 메시지 등 텍스트에서 사용하는 마침표(.)를 제거한다.

### 🔥 할 일
- [ ] 점을 뺀다.

### ⏰ 예상 시간
- 

### 🐴 할 말
- 다 같이 화면을 보면서 한 번에 정리하는 시간을 가지면 좋을 것 같아요.

**Comment by donghoony** [comment]
점뺀다면서 제목에는 점이 있어요
