### ISSUE TITLE
[BE] 예외 클래스가 올바른 패키지에 있는지 점검한다.

### ISSUE THREAD

**Issue by nayonsoso** [woowacourse-teams/2024-review-me#439]
### 🔍 설명
- 지금은 예외 클래스가 service.excetpion 과 domain.exception 으로 있으며
- 그 기준이 모호하게 되어있습니다!
- 처음에 모든 로직을 도메인에 넣었던 설계의 레거시라는 생각도 듭니다 ㅎㅎ

### 🔥 할 일
- 예외를 적절히 분류합니다!

### ⏰ 예상 시간
- 1시간

### 🐴 할 말
-

**Comment by donghoony** [comment]
이거 잘 해결되었나요 ? 🤔

**Comment by donghoony** [comment]
- #592

위 PR에서 어느정도 해소되었다고 생각해 이슈를 닫습니다 😁
