### ISSUE TITLE
[BE] 서비스의 검증 로직을 도메인으로 위임하기위해 양방향 연관관계 도입이 필요한 상황에 대해 논의한다.

### ISSUE THREAD

**Issue by hyeonji1220** [woowacourse-teams/2024-review-me#49]
### 🔍 설명
- 서비스의 검증 로직을 도메인으로 위임하기위해 양방향 연관관계 도입이 필요한 상황에 대해 논의한다.
https://github.com/woowacourse-teams/2024-review-me/pull/45#discussion_r1683725546

### 🔥 할 일
- 서비스의 검증 로직을 도메인으로 위임하기위해 양방향 연관관계 도입이 필요한 상황에 대해 논의하고 코드에 적용하기

### ⏰ 예상 시간
- 1시간

### 🐴 할 말
- 객체적인 관점과 JPA를 어떻게 잘 조화시킬 수 있을까요이이히힝

**Comment by donghoony** [comment]
#83
