### ISSUE TITLE
[FE] 캐러셀의 마지막 슬라이드에 도달했을 때 애니메이션 전환이 부자연스러운 문제를 해결한다.

### ISSUE THREAD

**Issue by ImxYJL** [woowacourse-teams/2024-review-me#507]
### 🔍 설명
- 제곧내

### 🔥 할 일
- 캐러셀이 마지막에는 바로 첫 슬라이드로 이동해야 하는데 기존 슬라이드들을 거슬러 올라가고 있습니다

### ⏰ 예상 시간
- ??

### 🐴 할 말
- CD 되게 해주세요

**Comment by donghoony** [comment]
오 이거 이야기하려고 했는데 대박박박
