### ISSUE TITLE
[BE] DB Schema 파일을 생성하고, Flyway를 적용한다.(dev → prod)

### ISSUE THREAD

**Issue by Kimprodp** [woowacourse-teams/2024-review-me#516]
### 🔍 설명
- 엔티티 컬럼에 변경사항이 있을 경우, ddl auto validate 설정으로 인하여 테이블과 설정이 맞지 않아 에러가 발생합니다.
- 이 경우 DB에 직접 컬럼을 설정해주어야 하는데, 스키마 파일로 관리하기 위해 해당 파일을 생성합니다.

### 🔥 할 일
- [x] schema.sql 추가
   - validate 옵션이기에 원래라면 schema.sql로 테이블이 생성되었어야 함. 현재 테이블이 해당 sql을 바탕으로 생성되었다는 명시이기도 함.
- [x] flyway 설정 추가 (dev)
- [ ] flyway 설정 추가 (prod)
- [x] dev validate 변경

### ⏰ 예상 시간
- 1h 

### 🐴 할 말
-

**Comment by donghoony** [comment]
`validate`로 해 두어서 `init.sql`을 형상관리 해두어야겠습니다 👍🏻

**Comment by donghoony** [comment]
flyway 도입도 해야겠습니다
