### ISSUE TITLE
[BE] CORS를 프론트 서버 주소로만 제한한다.

### ISSUE THREAD

**Issue by hyeonji1220** [woowacourse-teams/2024-review-me#583]
### 🔍 설명
- 현재 cors가 와일드카드로 설정되어있습니다. 프론트 주소로만 제한해야하지 않을까요?

### 🔥 할 일
- CORS를 프론트 서버 주소로만 제한한다.

### ⏰ 예상 시간
- 30m

### 🐴 할 말
1. (산초 예시) 만약 악덕개발자가 우리 서비스 클론 코딩하려고 프론트만 따로 만들어서 우리 api에 요청 보내면 안되니까

**Comment by donghoony** [comment]
- #666 을 진행하면서 보안 상 함께 처리되었습니다 ✅

**Comment by donghoony** [comment]
- #666 을 진행하면서 보안 상 함께 처리되었습니다 ✅
