### ISSUE TITLE
[BE] 사용하지 않는 일급 컬렉션을 삭제한다.

### ISSUE THREAD

**Issue by hyeonji1220** [woowacourse-teams/2024-review-me#588]
### 🔍 설명
- 살펴보다 보니 CheckboxAnswers클래스를 전혀 사용하지 않고 있더라고요. 너무 작은 커밋이라 다른 리팩토링 할 것 있으면 함께 진행하면 좋을 것 같아요!

### 🔥 할 일
- CheckboxAnswers, CheckboxAnswers 클래스 삭제

### ⏰ 예상 시간
- 5m

### 🐴 할 말
-

**Comment by donghoony** [comment]
현재 Production level 코드에 존재하지 않으므로 해당 issue는 닫습니다.
