### ISSUE TITLE
[BE] 리뷰 조회 페이지에 세션을 적용한다.

### ISSUE THREAD

**Issue by donghoony** [woowacourse-teams/2024-review-me#600]
### 🔍 설명
- 현재 리뷰 조회 시, 새로고침을 하게 되면 사용자는 인증 정보가 없다는 메시지를 받습니다.
- 비밀번호를 로컬에 저장하는 건 좋은 생각은 아닙니다. 탈취의 가능성도 있고, 민감한 정보를 암호화하지 않고 프론트의 책임으로 돌려 두는 것 보다 더 나은 선택지가 있다고 생각했어요.
- 세션, 토큰 두 가지 선택지가 있었어요. 처음에는 단순하게 세션을 활용하면 되겠다고 생각했어요. 세션과 토큰 둘 다 보안 측면에서는 비슷했어요. 탈취 등의 문제는 ~~(당한 사람이 잘못이에요)~~ 유효 기간을 둘 다 설정해둘 수 있습니다.
- 세션에서 발생할 수 있는 문제로 여러 탭에서 다중 리뷰를 확인할 수 없다는 점이었습니다. 다만 이건 토큰을 로컬에 보관하는 것도 마찬가지예요.

- 문제 상황은 결국 리뷰 조회 시 새로고침한다면 리뷰를 다시 볼 수 없는 문제이므로, 이를 세션을 통해 해결하고자 합니다.

### 🔥 할 일
- 리뷰 조회 요청 시, 세션을 생성하고 이를 기반으로 리뷰 내용을 확인

### ⏰ 예상 시간
- 3h+

### 🐴 할 말
- 토큰이냐 세션이냐 그것이 문제로다... 아니 사실은 문제가 문제가 아니었다?!

<br><br><br><br><br><br>
(아래는 수정 전 이슈 본문입니다)

---

### 🔍 설명
- `GroupAccessCode`가 필요할 때, 프론트에서 헤더를 통해 전달합니다. 다만 이 항목은 브라우저에서 저장하고 있기에 민감한 정보이므로, 이를 토큰을 사용하도록 합니다.
- 비밀번호는 영구히 탈취될 가능성이 있으나, 토큰의 경우는 만료 기한까지만 유효하므로 좋아요 👍🏻 

### 🔥 할 일
- 기존 헤더에 비밀번호를 담는 것을 토큰을 담도록 변경

### ⏰ 예상 시간
- 2-3h

### 🐴 할 말
- 감회가 새로운 토큰 발급 👶🏻

**Comment by hyeonji1220** [comment]
GroupAccessCode가 아니라 ReviewRequestCode를 토큰에 담아주기로 한 변경 사항이 반영되면 좋을 것 같아요~
