### ISSUE TITLE
[FE] 작성 페이지의 LCP, FCP 수치를 개선한다.

### ISSUE THREAD

**Issue by chysis** [woowacourse-teams/2024-review-me#604]
### 🔍 설명
- 네트워크 제한 없음 상태에서 lighthouse 기준으로 리뷰 작성 페이지의 LCP는 3.3초, FCP는 1.7초를 기록하고 있습니다.
- 빠른 페이지 로딩을 위해 LCP는 2초, FCP는 1초에 근접하도록 성능을 개선하는 것이 목표입니다.

### 🔥 할 일
- 리뷰 작성 페이지의 성능을 최적화하여 LCP 및 FCP 수치를 줄입니다.

### ⏰ 예상 시간
- 1시간 안으로 끝내봅시다.

### 🐴 할 말
- 🏝️

**Comment by BadaHertz52** [comment]
js 압축으로 해결

![image](https://github.com/user-attachments/assets/ed4ff0c5-4cfc-4857-83e7-f3c34ea0c5dc)
