### ISSUE TITLE
[BE] 네이티브 쿼리에서 테이블.*로 되어있는 부분을 구체적인 컬럼으로 변경한다.

### ISSUE THREAD

**Issue by hyeonji1220** [woowacourse-teams/2024-review-me#624]
### 🔍 설명
-  네이티브 쿼리에서 테이블.*로 되어있는 부분을 구체적인 컬럼으로 변경한다.

### 🔥 할 일
- 네이티브 쿼리에서 id를 반환해야하는 메서드를 다음과 같이 q.*로 작성한 부분이 꽤 있습니다.
- 이전에 q.*로 했다가 Question의 다른 long 타입인 position을 가져왔던 오류가 있었기에 이러한 오류를 방지하기 위해 q.id 형식으로 가져오는 컬럼을 구체적으로 명시하려고 합니다!
```sql
    @Query(value = """
            SELECT q.* FROM question q
            LEFT JOIN section_question sq
            ON sq.question_id = q.id
            WHERE sq.section_id = :sectionId
            ORDER BY q.position ASC
            """, nativeQuery = true)
    List<Question> findAllBySectionId(long sectionId);
```

### ⏰ 예상 시간
- 20m

### 🐴 할 말
-

**Comment by skylar1220** [comment]
이미 다 잘 적용되어있네요^^😇😇😇
착각했습니당ㅎㅎ

**Comment by hyeonji1220** [comment]
이미 다 잘 적용되어있네요^^😇😇😇
착각했습니당ㅎㅎ
