### ISSUE TITLE
[BE] OSIV disable 여부를 논의한다.

### ISSUE THREAD

**Issue by hyeonji1220** [woowacourse-teams/2024-review-me#664]
### 🔍 설명
- 서버가 다시 뜰 때마다 warn에 osiv diable하라는 로그가 찍혀서 발견했어요
![image](https://github.com/user-attachments/assets/19754884-06c1-4a1d-9745-10ba89a97798)
- 하루에 cd가 10번 돌아가면 10번 warn이 쌓일거고 알림이 올텐데라는 생각이 들었어요. 어떤 결정을 하는 것이 좋을지 논의해보고 싶어요!
1. osiv diable을 고려해본다. (커넥션 낭비를 고려해서)
2. osiv 관련 warn은 무시한다.

### 🔥 할 일
- 백엔드 논의

### ⏰ 예상 시간
- 30m?

### 🐴 할 말
-

**Comment by donghoony** [comment]
false 하는 게 더 좋겠네요~

**Comment by donghoony** [comment]
#671 에서 해결될 예정입니다.
