### ISSUE TITLE
[BE] dialect 설정 여부를 논의하고 불필요시 삭제한다.

### ISSUE THREAD

**Issue by hyeonji1220** [woowacourse-teams/2024-review-me#665]
### 🔍 설명
- warn에 dialect 설정을 하지 않아도 된다는 로그가 기록되고 있습니다. 해당 설정을 하지 않아도 되는 건지 확인해보고 없어도 되면 제거하면 되겠습니다!
![image](https://github.com/user-attachments/assets/aea8a988-c8da-4a0f-9231-4367171cb377)

### 🔥 할 일
- dialect 설정을 해주지 않아도 되는 건지 확인
- 없어도 되면 yml에서 삭제

### ⏰ 예상 시간
- 1h

### 🐴 할 말
-

**Comment by donghoony** [comment]
이거 처음에는 없으면 오류 뻗어서 넣으면 되었다가, 두번째부터 deprecated 오류가 튀어나왔던 걸로 기억하는데.. 확실하지는 않습니다 🥲

-> Dialect 오류는 DB 접속 실패 시에도 받아볼 수 있는 상황입니다. `deprecated`되는 옵션에 따라 개발 서버부터 하나씩 지워서 확인해볼게요 (2024/11/14)

**Comment by donghoony** [comment]
https://github.com/woowacourse-teams/2024-review-me-secret/commit/41928e6d8eb70ee548469aaccf2c90417b746647

**Comment by donghoony** [comment]
prod에는 이미 dialect 속성이 존재하지 않네요~ 이슈 닫겠습니다 👍🏻
