### ISSUE TITLE
[BE] Dockerfile 추가

### ISSUE THREAD

**Issue by Kimprodp** [woowacourse-teams/2024-review-me#670]
### 🔍 설명
- 프로젝트의 도커 파일 생성을 위한 Dockerfile을 추가합니다.

### 🔥 할 일
- root 경로에 Dockerfile 추가

### ⏰ 예상 시간
- 5m

### 🐴 할 말
-

**Comment by donghoony** [comment]
5m ?? ? ? ?? ????? ?? ? ?
