### ISSUE TITLE
[BE] 리뷰 상세 보기에서 불필요한 min, max, isChecked 속성 삭제한다.

### ISSUE THREAD

**Issue by hyeonji1220** [woowacourse-teams/2024-review-me#774]
### 🔍 설명
- 리뷰 상세 보기에서 불필요한 min, max, isChecked 속성 삭제한다.

### 🔥 할 일
- 

### ⏰ 예상 시간
- 

### 🐴 할 말
-

**Comment by donghoony** [comment]
closing due to a duplicate of:
- #731
