### ISSUE TITLE
[BE] 비용 절감을 위해서 dev EC2 의 서브넷을 private 서브넷으로 옮기고, 퍼블릭 IPv4 를 해제한다.

### ISSUE THREAD

**Issue by nayonsoso** [woowacourse-teams/2024-review-me#777]
#### 배경 
- 개발 ec2 를 lb 아래에 두고, bastion 을 사용해서 접근하도록 변경을 했었다.
- 이에 따라 public IPv4 가 더 이상 필요하지 않게 되어서 EIP 를 해제해주었다.
- 하지만, 이 변경 이후 깃허브 러너가 실행되지 않는 문제가 발생했다.

#### 원인
- 원인은 EIP 를 해제함에 따라서 dev-ec2 가 인터넷에 접속하지 못하는 것 때문이었다.
- "그렇다면 EIP 가 없는 다른 ec2(e.g. prod-ec2) 는 어떻게 CI 가 작동했지?" 하니,
- prod-ec2 는 서브넷이 project-app 이었고, 이 서브넷에는 NAT 가 연결되어있었기 때문에 가능했다.

#### 논의
- 문제를 파악한 우리는 dev-ec2에 EIP를 할당할지, 아니면 dev-ec2 를 project-app 으로 옮길지 고민을 했으나,
- 시간 부족으로 인해 EIP 를 할당하기로 했다.
- 비록 월 3.65 달러가 추가로 부과되긴 하지만, 돈으로 시간을 샀다!!

![image](https://github.com/user-attachments/assets/e1b9cb01-e82b-44f3-880e-1f2b304110c5)

### 🔥 할 일
- 비용 절감을 위해서 dev EC2 의 서브넷을 private 서브넷으로 옮기고, 퍼블릭 IPv4 를 해제한다.

### ⏰ 예상 시간
- 2h

### 🐴 할 말
- 퍼블릭 IP 가 없으면 인터넷 게이트웨이가 있어도 사용을 못하는구나..
- 왜 있어도 쓰질 못하니!!!

**Comment by donghoony** [comment]
인프라 환경 이동에 따라 해당 Issue는 닫겠습니다!
- #960
