### ISSUE TITLE
[BE] API 수정사항을 반영한다.

### ISSUE THREAD

**Issue by hyeonji1220** [woowacourse-teams/2024-review-me#82]
### 🔍 설명
- API 수정사항을 반영한다.

### 🔥 할 일
- uri 매핑을 수정한다.
- DTO 파라미터들을 수정한다.

### ⏰ 예상 시간
- 1시간 같은 2시간

### 🐴 할 말
- 가자아아아

**Comment by donghoony** [comment]
#57 반드시 해야한다 🔥
