### ISSUE TITLE
[BE] 에러 메시지의 오타를 수정하고 하이라이트 수정 시 delete 쿼리를 한번만 나가도록 한다.

### ISSUE THREAD

**Issue by hyeonji1220** [woowacourse-teams/2024-review-me#832]
### 🔍 설명
- 에러 메시지의 오타를 수정하고 delete 쿼리를 한번만 나가도록 한다.

### 🔥 할 일
- 에러 메시지의 오타를 수정하고 delete 쿼리를 한번만 나가도록 한다.

### ⏰ 예상 시간
- 

### 🐴 할 말
-

**Comment by donghoony** [comment]
- #833 
- #850 
- #859
