### ISSUE TITLE
[BE] 리뷰 상세 조회 dto 개선

### ISSUE THREAD

**Issue by Kimprodp** [woowacourse-teams/2024-review-me#846]
### 🔍 설명
- 리뷰 상세 조회에서 사용되지 않는 불필요한 항목이 존재하여 제거합니다.
- optionGroupId, minCount, maxCount, isChecked
- 옵션 그룹 없이 선택 항목만 내려줘도 될 것 같습니다.

### 🔥 할 일
- 

### ⏰ 예상 시간
- 10m

### 🐴 할 말
-

**Comment by donghoony** [comment]
프론트 쪽에서 인지하고 사용 안 하는 버전이 올라갔을 때 머지해야 합니다 ~!

**Comment by donghoony** [comment]
이미 있는 이슈입니다 ㅎㅎㅎ
- #731 
- #774

**Comment by Kimprodp** [comment]
헉 그렇군요 
머지는 프론트 협의 후 머지합니다~

**Comment by donghoony** [comment]
closing due to duplicates of:
- #731
- #774
