### ISSUE TITLE
[All] 리드미용 이미지를 업로드한다.

### ISSUE THREAD

**Issue by hyeonji1220** [woowacourse-teams/2024-review-me#918]
### 🔍 설명
- 

### 🔥 할 일
- 

### ⏰ 예상 시간
- 

### 🐴 할 말

![img_4](https://github.com/user-attachments/assets/7e07e607-1934-4681-91b8-49b776ac4f77)
![img_5](https://github.com/user-attachments/assets/14a80d0a-9025-4afe-919e-5cd2d044ba99)
![img](https://github.com/user-attachments/assets/8cbb5abb-c989-47d2-8dc1-02689b2b3683)

![img_3](https://github.com/user-attachments/assets/51508952-6b3e-493b-9404-0e5585b91e8e)

![img_1](https://github.com/user-attachments/assets/8624099f-69ed-4b31-84bb-a6bc4321f0ba)

![img_2](https://github.com/user-attachments/assets/741111ba-d682-4306-9f7c-716cfa3ff6a7)

![image](https://github.com/user-attachments/assets/0a7aa302-b737-496d-9fec-54a8088da3b5)
![image](https://github.com/user-attachments/assets/7ed2c55e-7dd2-43bf-918d-69a8bd87ef68)

![Group 241](https://github.com/user-attachments/assets/7794eb6a-5d04-4c21-b1f5-da5904de02ee)

![image](https://github.com/user-attachments/assets/9753d451-42d9-4b9e-b483-1c34b5839464)

![프론트엔드 기술 스택 (1)](https://github.com/user-attachments/assets/7497d615-02f5-48e6-b5a2-847121c56df8)

![수정본](https://github.com/user-attachments/assets/acb9899f-4483-4505-928a-2458062c355a)

**Comment by donghoony** [comment]
- #927
