### ISSUE TITLE
[All] v2.0.2  리뷰미 배포

### ISSUE THREAD

**Issue by BadaHertz52** [woowacourse-teams/2024-review-me#928]
### 🔍 설명
- [x] 형광펜 버그 수정 
 - ios 형광펜 안됨 및 위치 버그 해결
  - 형광펜 색상 변경
- [x] 로고 스크린 리더기 오류 수정
- [x] URL 모달 뒤로 가기 막기
- [x] 차트 내림차순 정렬 

### 🔥 할 일
- 

### ⏰ 예상 시간
- 

### 🐴 할 말
-

**Comment by donghoony** [comment]
- #929
