### ISSUE TITLE
[BE] TooManyRequest 요청을 로깅할 때, LB 에서 전달되는 X-Forwarded-For 헤더를 추출하여 공인 IP를 기록한다.

### ISSUE THREAD

**Issue by nayonsoso** [woowacourse-teams/2024-review-me#943]
### 🔍 설명
- 현재는 로드벨런서의 IP 를 remoteAddress 로 로깅하고 있습니다.
- 이는 의미가 없으며.. LB 가 서버에 전달할 때 전해주는 X-Forwarded-For 헤더에서 진짜 IP 를 알 수 있습니다.
- 이를 위한 리팩터링을 진행합니다. 

### 🔥 할 일
- RequestLimitInterceptor 의 코드를 수정합니다.

### ⏰ 예상 시간
- 15분

**Comment by donghoony** [comment]
Nginx에서 해당 내용을 처리하기로 결정함에 따라 해당 이슈 close할게요~
